[build]
  publish = "public"

[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/doctors"
  to = "/doctors.html"
  status = 200

[[redirects]]
  from = "/gallery"
  to = "/gallery.html"
  status = 200

[[redirects]]
  from = "/pricing"
  to = "/pricing.html"
  status = 200

[[redirects]]
  from = "/reviews"
  to = "/reviews.html"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 200

[[redirects]]
  from = "/faq"
  to = "/faq.html"
  status = 200

[[redirects]]
  from = "/services"
  to = "/services.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/contactsubmit"
  to = "/thank-you.html"
  status = 301

[[redirects]]
  from = "/CarrerSubmit"
  to = "/thank-you.html"
  status = 301
